name: editorconfig

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: EditorConfig-Action
        uses: zbeekman/EditorConfig-Action@v1.1.1