name: editorconfig

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - name: EditorConfig-Action
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'